stages:
    - build
    - test

build:
   stage: build
   script:
    - call ./fips fetch
    - call ./fips update
    - call ./fips nebula set work ../fips-deploy/
    - call ./fips nebula set toolkit .
    - call ./fips set config vulkan-win64-vs2017-debug
    - call ./fips gen
    - call ./fips build

test:
   stage: test
   script:
    - call ./fips set config vulkan-win64-vs2017-debug
    - call ./fips physx deploy
    - call ./fips run testfoundation
    - call ./fips run testmath
    - call ./fips run testgame
