before_script:
    - call ./fips fetch
    - call ./fips update
    - call ./fips nebula set work ../fips-deploy/
    - call ./fips nebula set toolkit .
    
stages:
    - build

build:
   stage: build
   script:
    - call ./fips set config vulkan-win64-vs2017-debug
    - call ./fips gen
    - call ./fips build
    - call ../fips-deploy/nebula-tests/vulkan-win64-vs2017-debug/testfoundation
    - call ../fips-deploy/nebula-tests/vulkan-win64-vs2017-debug/testgame
    - call ../fips-deploy/nebula-tests/vulkan-win64-vs2017-debug/testmath
